### ISSUE TITLE
BTCST 安定版の32bit版配布希望

### ISSUE THREAD

**Issue by terrycoffe** [emu8/BTCST#101]
タイトルの通りです。

discordのupdateリンクから配布されてる安定版は64bitのみのようなので32bit版の配布を希望します。

ついでにブラウザ版も早くできると嬉しいです！

**Comment by ghost** [comment]
ver1.01-build_003で32bit版の廃止を行いました。
開発効率の上昇ならびに、今後OSは32bitが廃止に向かい64bitがスタンダードになることが理由です。
よろしくお願いいたします。
