### ISSUE TITLE
MEX版BTCSTでブラウザ側でポジションが反映されない。

### ISSUE THREAD

**Issue by mixixk** [emu8/BTCST#102]
## 内容
ショートをエントリーしていますがBTCSTのウィンドウでは「評価損益:ポジションが存在していません」と表記されます。
![image 1](https://user-images.githubusercontent.com/39526811/43873244-ce2c8732-9bc0-11e8-8adf-5ae76b60413b.png)

**Comment by ghost** [comment]
この問題については、現在テスター様向けにリリースしているBTCST for BitMEXの新ビルドで解決しております。
ご不便をおかけしますが今しばらく正式版リリースまでお待ちください。
