### ISSUE TITLE
BTCST初回起動時の既定数量を0.001にしていただけないでしょうか

### ISSUE THREAD

**Issue by freestart** [emu8/BTCST#14]
BTCSTを初回起動したとき、既定数量が１となっております
１BTCが現状２００万円ですので、初心者にとって大きな金額だと思います
数量変更を忘れてトレードしてしまうと一瞬でロスカットの危険があります
できれば初期既定数量を0.001に変更していただけないでしょうか

**Comment by ghost** [comment]
ver1.01-build_003で既定数量を現在の最小値 (0.01)にするよう修正を行いました。
