### ISSUE TITLE
バージョンアップ時の設定引き継ぎ

### ISSUE THREAD

**Issue by hinotori-JG** [emu8/BTCST#18]
可能でしたらバージョンアップした時に各種設定を引き継げるようにして欲しいです。
ご検討ください。

**Comment by ryght** [comment]
こちらの方法で対応をお願いいたします。

※更新の際、アプリ上の現在の設定を引き継ぐ方法（今回のような大幅なUIの変更などを伴わない更新の場合のみ可能）

1. インストールフォルダ上の　app-　で始まる設定ファイル（５ファイル）を、app-version.conf　以外、どこかのフォルダへコピーしバックアップをとっておきます
1. 通常の手順でアプリケーションを更新します
1. 一旦アプリケーションを起動し、ログインした後、終了させます
1. バックアップしていたファイルをインストールフォルダへ上書きコピーします。
1. 再度アプリケーションを起動し、ログインします
