### ISSUE TITLE
自動利確時の2重注文について

### ISSUE THREAD

**Issue by hayanobiton** [emu8/BTCST#19]
先程の落下の最中に、差しておいて注文が約定し、自動利確機能により、売り注文が約定しました。

その後履歴をみたら、以下の売り注文が2重に入っておりました。
![1](https://user-images.githubusercontent.com/34781980/34315331-8aecbe1e-e7c1-11e7-9e50-799cd9bcf916.png)

設定を見たら
![2](https://user-images.githubusercontent.com/34781980/34315378-1ff1f4b6-e7c2-11e7-9de4-f514af2c7fbc.png)
と、損切り幅設定が50000だったため、この設定により注文がでたようす。

今回はそれよりもさらに下がったので今回予想外の利益をでましたが、それが逆に反発したらとおもうとぞっとしました。

仕様通りなのか、想定外なのかわかりませんが、ご報告させて頂きます

**Comment by ghost** [comment]
v1.01より、大幅な動作の軽量化・注文処理の正常化ならびに内部処理の最適化によるハングアップ・エラー等の対策を行いました。
最新のbuildで同現象が再度発生した際にもう一度issue投稿いただけますと幸いです。
