### ISSUE TITLE
注文ポジションウィンドウが強制スクロールされている件

### ISSUE THREAD

**Issue by hiro0306** [emu8/BTCST#20]
ナンピン注文を多く入れるまで気付かなかったのですが、注文ポジションのウィンドウが強制するロールされていて、上の方の指値額が確認出来ないようです。

060verで｢残分入れ直し｣ボタンの下のウィンドウです。

優先順位は最低ランクですが、一応報告致します。

**Comment by ghost** [comment]
ver1.01 build021にてオーダウィンドウの強制スクロール問題を修正しました。
