### ISSUE TITLE
自動利確時の処理が止まる場合があります。

### ISSUE THREAD

**Issue by dokandokankotu** [emu8/BTCST#23]
恐らくBTCST側で注文を飛ばして、
ローカルサーバ側でも受付できたがbFの注文にはなっていないという状態だと思います。

一例として
![1](https://user-images.githubusercontent.com/34842339/34342738-d719f1a2-e9fc-11e7-96ad-e022886131b8.png)
![2](https://user-images.githubusercontent.com/34842339/34342739-f3dfdebe-e9fc-11e7-9d9d-c050783ff346.png)

この設定で、自動仕込していましたが21:08:43の注文後に利確されず
手動決済するまで利確待ち？のような状態でした。手動決済すると自動仕込は動きますし、
利確されない状態になっていても損切も動きます。

該当部分のログ
[btcstlog.txt](https://github.com/emu8/BTCST/files/1586134/btcstlog.txt)
ローカルサーバ側のログはリロードしてるのでとれませんでした。どこかに保存されてるのかな？

注文時のチャート
![rikaku](https://user-images.githubusercontent.com/34842339/34342801-0337ffa2-e9ff-11e7-88c3-65f0577302fc.png)

その後何度か上に行ってるので利確されずに取り残されたというわけではなさそうです。

**Comment by dokandokankotu** [comment]
もしかしたらローカルサーバ側のログにはマーケット云々というのが出てるのかもしれません。
その場合は#5の改良で直りそうです。

**Comment by ryght** [comment]
build_065にて、bF側が注文を受け付けなかった場合、再注文を行うことでこの問題に対応しました。
