### ISSUE TITLE
損切ができない

### ISSUE THREAD

**Issue by Sakuramochiq** [emu8/BTCST#28]
![171228](https://user-images.githubusercontent.com/34910755/34406901-de0a7b04-ebfe-11e7-91eb-8ea73ec0f7f1.png)
画像の設定で損切幅を10万にしたのですが、
超えても損切をしてませんでした。

あと、
その時のポジション
12/28 09:30:03	FX BTC/JPY	買い	0.001	2209010		取引済
12/28 09:47:47	FX BTC/JPY	買い	0.002	2188534		取引済
12/28 10:25:35	FX BTC/JPY	売り	0.001	2219791		取引済←最初のポジションが自動利確
12/28 11:35:49	FX BTC/JPY	買い	0.003	2151009		取引済
12/28 11:44:18	FX BTC/JPY	買い	0.004	2118559		取引済
12/28 15:05:14	FX BTC/JPY	売り	0.009	1885001		取引済←手動で損切

BTCSTログ
2017/12/28 9:26:53: 自動仕込み処理を開始しました
2017/12/28 9:26:53: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:26:53: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:26:53: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:26:54: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:26:57: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:26:59: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:26:59: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:26:59: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:27:01: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:27:02: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:27:03: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:27:03: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:27:16: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:27:18: 自動仕込み処理が完了しました
2017/12/28 9:27:18: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:30:03: 自動利確指値注文を利益幅289で送信しました
2017/12/28 9:30:03: 注文は正常に受け付けられました(via browser extension)
2017/12/28 9:45:50: 127.0.0.1:64871との接続を切断しました
2017/12/28 9:45:52: 127.0.0.1:65098と接続しました
2017/12/28 10:15:50: 127.0.0.1:65098との接続を切断しました
2017/12/28 10:15:52: 127.0.0.1:65319と接続しました
2017/12/28 10:45:50: 127.0.0.1:65319との接続を切断しました
2017/12/28 10:45:52: 127.0.0.1:49168と接続しました
2017/12/28 11:15:50: 127.0.0.1:49168との接続を切断しました
2017/12/28 11:15:52: 127.0.0.1:49386と接続しました
2017/12/28 11:44:23: フルナンピン時自動建値逃げ指値注文を利益幅29873.8888888889で送信しました
2017/12/28 11:44:24: 注文は正常に受け付けられました(via browser extension)
2017/12/28 11:44:52: フルナンピン時自動建値逃げ指値注文を利益幅74867で送信しました
2017/12/28 11:44:53: 注文は正常に受け付けられました(via browser extension)
中略（手動で損切りするまで、フルナンピン時自動建値逃げ指値注文を利益幅74867で送信しましたの繰り返し）
2017/12/28 15:05:14: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました

となっていました。

**Comment by ryght** [comment]
「設定幅をこえても決済しない」という問題について
以下の類似issueに統合いたしました。
https://github.com/emu8/BTCST/issues/30
