### ISSUE TITLE
自動仕込みが、利確条件を満たしても決済されない場合がある

### ISSUE THREAD

**Issue by Letasun** [emu8/BTCST#30]
長時間放置、帰宅後に見たら利確条件（画像の2000）を大幅に超えて満たしているのに、
ポジションが決済されずに止まっている事がたまにあるのでご報告いたします。

全現在価格指値決済などで、現在のポジションを閉じると
自動で次の仕込みが入るのでツール自体が止まっている訳では無さそうです。

画像は、56442円幅となっているのに決済されていない状態です。

![default](https://user-images.githubusercontent.com/34898184/34447684-9d0bd9c8-ed29-11e7-8890-63247d23aa5a.jpg)

**Comment by aliyome** [comment]
類似の事象が発生したのでコメントとして報告します。

「現在利確中」が表示され続けててから20分くらい経っても利確されませんでした。
→ 手動で「全現在価格指値決済」を押下したところ、BTCSTのログに以下の内容が表示されました。
`2017/12/31 3:35:19: フルナンピン時自動建値逃げ指値注文を利益幅19416で送信しました`

もしかしたら、ナンピンの幅を持たせるために`,0`の設定を使うとフルナンピンと誤認識するケースがあるのかもしれません。
ナンピンはあと5段残っていました。ステルス利確もオフでした。
`1,2,3,4,5,0,6,7,0,8,0,9,0,10` ←の5段目まで到達

**Comment by ghost** [comment]
v1.01より、大幅な動作の軽量化・注文処理の正常化ならびに内部処理の最適化によるハングアップ・エラー等の対策を行いました。
最新のbuildで同現象が再度発生した際にもう一度issue投稿いただけますと幸いです。
