### ISSUE TITLE
ツールを一定時間放置していると、板情報が固まってしまう

### ISSUE THREAD

**Issue by yo-men** [emu8/BTCST#31]
以下、原因が分かれば教えてください（当方のネット環境が原因でしょうか）
一定時間ツールを放置してると、板情報が固まってしまい、そのまま数分待っても復活しない状態になってしまいます。
ｂｆが遅延しているわけでもなく、黒マチャートやいなごフライヤーは正常に動いているときが多いです。
関連があるかは分かりませんが、その際のログは以下のような表示が出ています。（この時は、いなごフライヤーのデータも、きちんとデータを取得していないような感じもありました）
![image](https://user-images.githubusercontent.com/34953360/34451170-927df31e-ed61-11e7-8ae1-e4acb2cc6513.png)

**Comment by emu8** [comment]
bF板同期機能によりこの問題に対応させていただきました。
