### ISSUE TITLE
ナンピン０について

### ISSUE THREAD

**Issue by ankokumen** [emu8/BTCST#33]
ナンピン０を使用して指値幅を調整していますが、幅をとるために０を多くすると一番遠くに指値を置くのに５分ほど時間がかかってしまいます。

そこで、ツール側でナンピン０を入れるとキャンセルしてｂF側に注文を送らない（飛ばし）のような使用に変更できませんでしょうか？

技術的なことはよくわかりませんが、『０』で注文を送らなければ軽くなるのかなっと思っています。

**Comment by ryght** [comment]
build_064にて対応しました。
