### ISSUE TITLE
最低利確幅を○○秒以上保持した場合、そのポジションで再注文を入れる

### ISSUE THREAD

**Issue by psytribes** [emu8/BTCST#35]
ナンピン使用時、利確幅を大きくもたせる為、最低利確幅以上の良い所で注文が入りますが
大きなヒゲの時は、一度注文が入ると中々再突入するタイミングがなく、
損益はプラス状態に入っているも
利確出来ないという勿体無い状態になるときが有ります
そこで、最低利確幅を○○秒以上保持した場合、そのポジションで再注文を入れるという機能は可能でしょうか？
今は「全キャンセル」を押して、再度自動指値注文してますので、
そのロジックが動けばいいと思います

**Comment by ghost** [comment]
ver. 1.01 build020にて現在利確中の表示が指定秒数継続した際の「全現在価格指値決済」機能を追加しました。
