### ISSUE TITLE
自動利確が行われない

### ISSUE THREAD

**Issue by minex87** [emu8/BTCST#39]
自動利確が行われない場合が多々あります。
最終的には自分で決済を行っています。
![btcst](https://user-images.githubusercontent.com/35192836/34649583-73da2294-f3f5-11e7-893e-d4cdea032c8c.png)
![default](https://user-images.githubusercontent.com/35192836/34649584-74eccfe2-f3f5-11e7-93a7-8d0f11b09599.png)
https://pastebin.com/eAmAsVbq

**Comment by emu8** [comment]
こちら画面では　動作ボタンが　停止　になっているのでそのせいかもしれません。
自動　になっていなければ自動処理は行われません。よろしくお願いします。
