### ISSUE TITLE
自動利確指値注文をするが実際には何もしない現象確認及び対処

### ISSUE THREAD

**Issue by krasherjoe** [emu8/BTCST#41]
「自動利確指値注文を利確幅xxxxで送信しました」
ログには上記の様に表示していますが、ある日を境に実際には注文しなくなります。
色々弄りましたが時間の無駄ですので app.conf(API/Secret) 以外を削除し、
BTCST〜.zipを再度展開して設定をやり直すのが手っ取り早いと思います。

**Comment by ryght** [comment]
bFの注文受付拒否による問題の可能性が高いです。
build_065にて、受付拒否をされても再注文を行う機能を追加いたしました。
