### ISSUE TITLE
自動利確が効かない

### ISSUE THREAD

**Issue by ankokumen** [emu8/BTCST#46]
本日、自動利確が効かない現象が現れましたので、報告致します。
エクセルファイルの黄着色した部分で、どうもおかしな動きあったようです。
一番上の段で、手動決済を行いました。

ツールのログは申し訳ないんですが、再起動を欠けたため残っておりません・・・。
スクショとエクセルを突き合わせてみると、下記のような感じです。
11：38　0.001約定
11：41　0.001の決済注文を送ったんですが、通らず
11：42　指値0.002約定
11：44　決済注文0.001約定
11：56　指値0.003約定

以後、現在利確中が続いていたと思われます。
12：31　0.005手動決済

![default](https://user-images.githubusercontent.com/34783734/34973118-41578c78-fac9-11e7-9ec0-11ef31167b11.png)
[自動利確出来ない.xlsx](https://github.com/emu8/BTCST/files/1633723/default.xlsx)

**Comment by emu8** [comment]
ありがとうございます。自動利確ですが、現状、一度でも自動決済注文がはいりますと、その後逆行し追加のナンピンが入った場合であっても最初の決済注文分しか処理されず、残りは手作業で決済しなければならないという仕様になっております。
将来的に、全ポジション解消されるまで賢く決済注文が入るようにしていきます。よろしくお願いします。

**Comment by ghost** [comment]
ver 1.01 build021にて自動仕込み指定秒数経過時、利確注文キャンセル設定を追加しました。

機能概要は以下のとおりです。
例 : 改善前
```
1. 0.01のLポジションに対して、利確注文0.01をステルスで発注。
2. 利確分が約定しないまま反対に動き、L方向の仕込み注文が複数約定。 (この時点でLポジションの合計が0.05とします)
3. 再度利確方向に動き、「1. 」で発注した利確注文0.01だけが利確される。
4. 差分の0.04が利確されず残る
```
例 : 改善後 (機能利用)
```
1. 0.01のLポジションに対して、利確注文0.01を発注。
2. 約定しないまま反対に動き、L方向の注文が複数約定。 (この時点でLポジションの合計が0.05とします)
**3. 利確注文キャンセル設定によって0.01の決済がキャンセルされ、キャンセル後に自動で0.05枚分の利確注文が入れ直される**
```
