### ISSUE TITLE
いなご自動売買でＢＴＣＳＴがフリーズする

### ISSUE THREAD

**Issue by kotetsu000** [emu8/BTCST#48]
いなごの自動売買でポジションを取る瞬間にBTCSTがフリーズします。
いなご自動売買ＯＮ
自動利確ＯＮ
両方ＯＮ
逆イナゴ損切り　ＯＮ
自動仕込み　ＯＦＦ
ブラウザ拡張を使用　ＯＮ
いなご時指値　ＯＦＦ
自動　ＯＮ
以上の設定でいなご自動売買のみで稼働していました。
尚、ナンピンのみの稼働では仕込みから利確までは異常は発生しませんでした。

ＢＴＣＳＴ　build_061
Windows10 64bit
フリーズ時のBTSCログ
2018/01/18 17:28:07: BTCST ver 1.00-build_061: initialized
2018/01/18 17:28:07: [1,"Connected","lightning_board_FX_BTC_JPY"]
2018/01/18 17:28:08: 127.0.0.1:60362と接続しました
2018/01/18 17:28:13: 127.0.0.1:60389と接続しました

フリーズ後にLightningにポジションは取っていないので
正確にはいなごの信号が入った瞬間にフリーズしているのかもしれません。

**Comment by kotetsu000** [comment]
build_062でも同じ症状が発生しました。
今回はノートとデスクトップでそれぞれ検証してみましたが、ノートパソコンのみ上記の不具合が発生することが判明しました。両方ともwin10 64bit 　メモリー8gbと同じ環境なのでドライバーとかの相性かもしれません。Windowsやドライバーなどアップデートできるものは全て試しましたがダメでした。

**Comment by kotetsu000** [comment]
ＢＴＣＳＴ　build_062で「いなごの自動売買でポジションを取る瞬間にBTCSTがフリーズします。」の検証を続けているのですが、デスクトップとノートパソコン共に「低解像度モード」で起動した場合にフリーズするようです。「高解像度モード」では問題は発生しませんでした。

**Comment by kotetsu000** [comment]
上記環境で
build_062の低解像度モードで損切り幅に到達した瞬間にもＢＴＳＣがフリーズします。
Lightningでは損切りされていませんでした。

**Comment by ryght** [comment]
ご不便をおかけしております。こちらのissueにて低解像度モードのハング原因を調査しています。
https://github.com/emu8/BTCST/issues/10
