### ISSUE TITLE
[build_061]フルナンピン時ログ上はプラス決済だが、マイナス決済している

### ISSUE THREAD

**Issue by Letasun** [emu8/BTCST#49]
気になる事があったので、低枚数でテストランしていた時に発見しましたので報告いたします。

![1](https://user-images.githubusercontent.com/34898184/35199639-1484d5d2-ff44-11e7-9487-18e953f8c415.jpg)
![2](https://user-images.githubusercontent.com/34898184/35199640-1630c558-ff44-11e7-8f3b-b0e934e005f7.jpg)

画像１，２共にフルナンピン時自動逃げ注文が利益幅＋で飛んでいるように見えます(BTCST)
また、その注文が正常に受け付けられ決済された様になっていますが
bitFlyerから損益のレポート（証拠金の変動）をダウンロードしてくるとマイナスで決済しています。

**Comment by ghost** [comment]
v1.01より、大幅な動作の軽量化・注文処理の正常化ならびに内部処理の最適化によるハングアップ・エラー等の対策を行いました。
最新のbuildで同現象が再度発生した際にもう一度issue投稿いただけますと幸いです。
