### ISSUE TITLE
【要望】利確幅、損切り幅について。スプレッドについて

### ISSUE THREAD

**Issue by ClamGBP** [emu8/BTCST#53]
イナゴ自動売買時の利確幅と損切り幅と、
ナンピン時の利確幅と損切り幅の設定を分けることは可能でしょうか？

またBfがスプレッド0.1パーセント以上に広がってるときはエントリーしないなどの機能が出来たら幸いです

**Comment by ryght** [comment]
利確/損切り幅について
以下の類似issueと統合しました。
https://github.com/emu8/BTCST/issues/22

スプレッドでエントリー制限について
以下の類似issueと統合しました。
https://github.com/emu8/BTCST/issues/66
