### ISSUE TITLE
【要望】＆【仕様上の不都合】いなご自動売買

### ISSUE THREAD

**Issue by jo100ss** [emu8/BTCST#55]
いなご自動売買の徹底検証を2週間ほど集中してやっています。
そこで仕様上の不都合らしく物を見つけたので報告致します。

【症状】いなご自動売買にて２重注文のようになる
詳細設定の「いなごエントリー後◯◯秒以上利確出来ない場合は強制決済する」の秒数を９秒以下にするとステルス利確を使用してる場合等、自動利確指値と時間切れ強制決済の値が近くになり結果的に２重注文のようになってしまう事がある。

【原因】予約注文キャンセルまでに値動きして指値に到達してしまう為
性質上仕方ないのかもしれないのですが時間が短いと高確率でなるので注意文を付けるか、同じ方向の注文が入った場合は即ポジション解消などした方が良いかもしれません。

【要望】スキャ対応の為のいなご設定の柔軟化
現仕様だと設定取引所のいなごに数値指定しシグナルを受ける細やかな設定がある反面、いなごの総量でシグナルを受ける設定がありません。スキャBOTに多いロジックの一つだと思うので是非実装してもらいたいです。
【要望２】BeryBusy時の自動系の一時停止機能
いなご自動売買だとBTCSTを持ってしてもBeryBusyだとエントリーから７秒以上の遅延するのが頻繁に起こるので大きな損益になりやすくサーバー状態に合わせての自動一時停止機能の実装もまたお願いしたいです。

以上長くなりましたがご報告でした。

**Comment by ryght** [comment]
自動利確併用時の二重注文について
重複するissueがあるため、以下に統合いたしました。
https://github.com/emu8/BTCST/issues/19

いなご総量でシグナルを受けるロジックについて
build_065にて同様のロジックが実装されました。

サーバーステータスで注文の一時停止を行う機能について
重複するissueがあるため、以下に統合いたしました。
https://github.com/emu8/BTCST/issues/66
