### ISSUE TITLE
【要望】自動仕込み時の最初の指値の位置について（２）

### ISSUE THREAD

**Issue by t4k4git** [emu8/BTCST#57]
現状の自動仕込み時の最初の指値について、例えばフィルタ30、ナンピン間隔5000としていた場合、

例：
現在価格100000
999000（壁50）
985000（壁50）

となっていれば、999000を飛び越えて現在価格から5000幅のところに指値がされますが、次の30枚以上の壁の手前に最初の指値を入れられるようになると（例では985000の手前）、壁を利用してナンピンなしで細かいスキャをする設定を行うにあたって戦略が広がるように思われます。
恐れ入りますが、ご検討の程よろしくお願いいたします。

**Comment by ryght** [comment]
以下issueと重複していたので統合いたしました。
https://github.com/emu8/BTCST/issues/45
