### ISSUE TITLE
「左右入替」ボタンの位置の変更

### ISSUE THREAD

**Issue by toto8toto** [emu8/BTCST#58]
「左右入替」ボタンの位置を現在の場所ではなく「リセット」ボタンの左側に移動してもらいたいです。
解像度1600x1200のVPSで使用するとちょうど左右入替ボタンが押せない位置で画面が切れてしまうので。

**Comment by ghost** [comment]
ver1.01-build_003で左右入替ボタンの配置を修正しました。
