### ISSUE TITLE
【機能追加要望】SFD向けのスキャル発注の機能追加（裁量支援）

### ISSUE THREAD

**Issue by toto8toto** [emu8/BTCST#62]
現在裁量支援ツールとして現指がすごく便利ですが、
SFD制度導入に伴い、SFD買とSFD売ボタンが欲しいです。
「SFD買」→現差価格に一番近い9.9%の価格で買い指値を出す。
「SFD売」→現差価格に一番近い10%の価格で売り指値を出す。
だと良さそうなのですがどうでしょうか？
リアルタイムで価格は動きますし乖離率も変わるのですが、
このボタンがあると現差と合わせて10%境界線付近での売買がしやすくなると思うので宜しくお願い致します。
BTCSTを使用すると勝ちやすいよねと言われるツールであり続けて欲しいです。

**Comment by ryght** [comment]
SFD関連機能は、現時点で乖離が広がる可能性が低いためリジェクトします。
