### ISSUE TITLE
【要望】SFD対策としての機能追加

### ISSUE THREAD

**Issue by kotetsu000** [emu8/BTCST#63]
SFDの比率に応じて自動仕込みを一時的にキャンセルする機能と損切り後に自動仕込みを停止する機能が欲しいです。SFDの比率が変化するときのせめぎあいが長期化する場合にもBTCSTを起動しやすくなると思います。

**Comment by ryght** [comment]
SFD関連機能は、現時点で乖離が広がる可能性が低いためリジェクトします。
「損切り後に自動仕込みを停止」機能については以下issueと重複しているため、統合いたします。
https://github.com/emu8/BTCST/issues/29
