### ISSUE TITLE
SFD境界でいなご自動のon/off切り替え, 逆いなごでドテン

### ISSUE THREAD

**Issue by toto8toto** [emu8/BTCST#65]
①「SFDの境界±0.5%ではイナゴ自動売買をオートオフにする」の機能が欲しいです。
10%付近や15%付近でイナゴ自動売買するとSFD手数料で損失になる可能性が高いので、SFD境界%に近付いたらイナゴ自動売買の新規エントリーをオフにする機能が欲しいです。
境界％から離れたら自動オンだとさらに助かります。

②「逆イナゴでドテン」の機能が欲しいです。
「逆イナゴで損切り」も活用してますが逆イナゴが鳴ったらその方向にもエントリーしたいのでドテン（損切り＋新規エントリー）の機能もあると助かります。

**Comment by ryght** [comment]
SFD境界でいなごon/off切り替えは、現時点で乖離が広がる可能性が低いためリジェクトします。

「逆いなごでドテン」に関しては以下issueと重複していたため、統合いたしました。
https://github.com/emu8/BTCST/issues/43
