### ISSUE TITLE
【要望】いなご自動売買の許容スプレッド設定とサーバーステータス許容設定

### ISSUE THREAD

**Issue by t4k4git** [emu8/BTCST#66]
いなご自動売買のエントリー時についての要望なのですが、成行でエントリーする都合上、エントリー時点に許容するスプレッドを設定できるようになるとありがたいです。
（スプレッド0.05以上ではエントリーしない、など）

また、可能であれば、サーバーステータスについても許容設定があると助かります。
是非、ご検討の程よろしくお願い致します。

サーバーステータスについて、類似の要望
>【要望２】BeryBusy時の自動系の一時停止機能
いなご自動売買だとBTCSTを持ってしてもBeryBusyだとエントリーから７秒以上の遅延するのが頻繁に起こるので大きな損益になりやすくサーバー状態に合わせての自動一時停止機能の実装もまたお願いしたいです。
___
>いなご自動売買を使用時に、マーケットがSUPER BUSY、BUZYなどで自動を一時停止する機能を望みます。遅延対策としてです。
よろしくお願い致します。

**Comment by ghost** [comment]
ver 1.01 build014にてサーバ状態でのいなご on / offを、
同build017にてスプレッド指定でのいなごon / offを追加しました。
