### ISSUE TITLE
v066 重複注文

### ISSUE THREAD

**Issue by ankokumen** [emu8/BTCST#70]
昨夜から今朝にかけてテストしたところ、重複注文が複数回あったようなので、報告致します。

また、一昨日v065をテスト放置していたところ、「自動利確指値注文（いなごv2ベータ版）を利益幅○○○で送信しました」を4時間程度にわたって繰り返されていました。
「送信しました」が複数回（10回程度？）出た場合は、一度キャンセル入れて利益幅送信を送るような処理がいいのではないでしょうか。
[Lightning_TradeHistory_20180403 (1).xlsx](https://github.com/emu8/BTCST/files/1869796/Lightning_TradeHistory_20180403.1.xlsx)

**Comment by ankokumen** [comment]
テスト発注数量は0.005です

**Comment by ghost** [comment]
ver1.01-build_003で重複注文時の対応を行いました。
