### ISSUE TITLE
【不具合】低解像度版でエラーがでてる。多分V2いなごも正常にうごかない模様。

### ISSUE THREAD

**Issue by Misoji-Kun** [emu8/BTCST#72]
## 留意点

- 1 issueにつき 1個の要望 / 報告を記載してください。  
複数の要望 / 報告がある場合は、項目ごとにissueの作成をお願いいたします。

- 報告の場合はBTCST設定画面のスクリーンショットを、画面下部の"selecting them"より添付してください。  
![image](https://user-images.githubusercontent.com/38009171/38298024-1866372e-3831-11e8-9e38-232ffe3dc641.jpg)

## 内容

ここには、どのような内容なのか記載してください。  
報告の場合は、再現手順 (どのようにすると不具合が発生したか)を、できるだけ詳しく記載してください。  

ログインするとでる。

## 実行環境 (報告のみ)
利用OS :  
BTCSTのbuild :  67
(わかる方のみ)  
利用PCの搭載CPU :  
利用PCの搭載メモリ量 :

**Comment by ghost** [comment]
ver1.01-build_003で低解像度版を削除しました。
