### ISSUE TITLE
低解像度版で設定値がずれて入力される

### ISSUE THREAD

**Issue by takk7** [emu8/BTCST#79]
## 内容
低解像度版で利用していますが、アプリを起動しなおす度に添付画像のように詳細設定の画面の設定値がずれて入力されています。
また、板情報の「フィルタ」の値も「False」になったりします。
入力し直して保存しても、終了して起動しなおすと、またずれています。
だいぶ前のバージョンからです。
（他の人の報告がないため、私の環境の問題なのかもしれませんが...）
よろしくお願いいたします。

## 実行環境 (報告のみ)
利用OS :  Windows Server 2016
BTCSTのbuild :  065
(わかる方のみ)  
利用PCの搭載CPU :  
利用PCの搭載メモリ量 :  4GB

<img width="920" alt="2018-04-16 20 28 32" src="https://user-images.githubusercontent.com/11170687/38808156-1812000e-41ba-11e8-8a1d-79d8369e54fe.png">

**Comment by ryght** [comment]
低解像度版の設定ファイルに異常がある可能性が高いです。
- 一度BTCSTのフォルダを消し、再度マイページよりダウンロードをして入れ直し作業を行う
- BTCSTを終了した状態で、BTCSTフォルダ内にある添付画像のファイル2種を消し、起動しなおす

このどちらかの作業を行っていただくことで問題が修正されるものと存じます。
**どちらの方法も、設定が初期化されますのでご注意ください**

お試しになっても問題が発生する際は、お手数ですがこのissueに再度コメントいただければと存じます。
以上よろしくお願いいたします。

![2018-04-17_00-32-34](https://user-images.githubusercontent.com/30257122/38819656-f2b8564c-41d6-11e8-8162-8911f1ec82cb.png)

**Comment by takk7** [comment]
ご回答ありがとうございます。

- BTCSTを終了した状態で、BTCSTフォルダ内にある添付画像のファイル2種を消し、起動しなおす

こちらを実施したところ、一旦は直りましたが、また再発しました。

いろいろ試してみて、再現方法が分かったのでお知らせします。

1. アプリを起動し、低解像度モードで接続する。
2. bF Lightningタブを開き、ログインする。
3. 板情報タブを開き、フィルタ値を変更する。
4. アプリを終了する。
5. アプリを起動し、低解像度モードで接続する。
6. 詳細設定タブを開く。

この手順で問題が発生しました。

回避方法が分かったので、急ぎではありません。
よろしくお願い致します。

**Comment by ryght** [comment]
症状と再現方法の報告ありがとうございます！
そちらの手順で当環境でも再現を確認できました。
ご迷惑をおかけしますが修正対応までお待ちください。

以上よろしくお願いいたします。

**Comment by ghost** [comment]
ver1.01-build_003にて低解像度版の廃止ならびに設定項目の保存について修正を行いました。
