### ISSUE TITLE
GMOで、ポジションを持っている状態でも、いなご自動による追加ポジションを持つように

### ISSUE THREAD

**Issue by emu8** [emu8/BTCST#8]
GMOで、ポジションを持っている状態でも、いなご自動による追加ポジションを持つようにできますか？
両建て手法を想定しています。
今現在両建て状態なのですが、いなごが鳴ったら追加新規ポジションを取るか決済するかしてもらえたら助かります。

**Comment by ghost** [comment]
GMOの各種規制および取引所としての信頼度の点から、GMO版のアップデートは停止しております。
