### ISSUE TITLE
バージョン65の利用について

### ISSUE THREAD

**Issue by gsriota** [emu8/BTCST#80]
お疲れ様です！
いつもお世話になっております。
V2等のツールの開発、日々ありがとうございます。

ところで、
64は、注文が通らなくなったようですが…
65は、使えなくなったりしないですよね？
元祖イナゴや裁量は、65の方が好調です。
65は永久利用できるように
何卒よろしくお願い致します。

**Comment by ryght** [comment]
過去verのようなものを永続的に利用できるようにしてほしい　という件について、
以下issueと重複する内容でしたので統合いたします。
https://github.com/emu8/BTCST/issues/73

現時点ではbuild065を利用できなくするといった予定はありませんが、bitFlyerのアップデートや重大なバグが見つかったなど、様々な理由で過去verが利用できなくなる可能性はございます。
しかし、多くの要望をいただいておりますので、build065が求められている理由などピックアップを行い、それに類するようなアップデートを行えるよう検討してまいります。
