### ISSUE TITLE
[v70]自動仕込の注文の途中で全キャンセルが入る

### ISSUE THREAD

**Issue by richio6624** [emu8/BTCST#82]
BTCSTを起動させて、自動仕込をロングのみで実施したところ下記のログのように途中で全キャンセルが入り注文が全て入りません。
ナンピン設定は「1,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,9,」に
していて、4,6,9に当たる部分がキャンセルになりました。
ただ必ずキャンセルが3つというわけではなく処理速度の違いかわかりませんが、
注文の途中で全キャンセルが多々入りすべての注文が受け付けられません。

2018/04/21 10:47:49: 自動仕込み処理を開始しました
2018/04/21 10:47:49: 自動仕込み処理が完了しました
2018/04/21 10:47:49: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:47:49: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:47:49: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:47:50: ** 全キャンセル要求が正常に受け付けられました
2018/04/21 10:47:50:  CH: 注文全キャンセル e6716b7a-3d07-487c-9054-a73f42c3fc47
2018/04/21 10:47:59: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:48:01: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:48:02: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）  

## 実行環境 (報告のみ)
利用OS :  win10
BTCSTのbuild :  070
(わかる方のみ)  
利用PCの搭載CPU :  corei5-2500(3.3GHz)
利用PCの搭載メモリ量 :  12G

**Comment by ghost** [comment]
v1.01より、自動仕込みなどの注文処理最適化を行い、想定通りの動作をするよう修正を行いました。
最新のverにて同現象が再度発生した際にもう一度issue投稿いただけますと幸いです。
