### ISSUE TITLE
[v70]自動利確できない

### ISSUE THREAD

**Issue by richio6624** [emu8/BTCST#83]
自動仕込みで注文が約定して、画像のように最低利確幅を超えて現在利確中となっているが
いつまでたっても利確されない。

![default](https://user-images.githubusercontent.com/35882330/39079538-b7f12c62-4557-11e8-8eb5-3d42dbb9368c.png)
 

## 実行環境 (報告のみ)
利用OS : win10
BTCSTのbuild : 070
(わかる方のみ)
利用PCの搭載CPU : corei5-2500(3.3GHz)
利用PCの搭載メモリ量 : 12G

## ログ (報告のみ)

2018/04/21 10:47:49: 自動仕込み処理を開始しました
2018/04/21 10:47:49: 自動仕込み処理が完了しました
2018/04/21 10:47:49: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:47:49: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:47:49: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:47:50: ** 全キャンセル要求が正常に受け付けられました
2018/04/21 10:47:50: CH: 注文全キャンセル e6716b7a-3d07-487c-9054-a73f42c3fc47
2018/04/21 10:47:59: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:48:01: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/21 10:48:02: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）

**Comment by ghost** [comment]
ver1.01-build_003にて利確不具合の修正を行いました。
