### ISSUE TITLE
070で自動利確が入ってすぐに全キャンセルが出て利確が消える時がある。

### ISSUE THREAD

**Issue by Sakuramochiq** [emu8/BTCST#84]
## 内容

いなごv2でステルス利確ONにして動かしていたところ、
自動利確が入ってすぐに全キャンセルが起こり、
利確注文が消えてしまいました。

その後、手動で利確するまで、
利確中と出ているだけでした。

## 実行環境 (報告のみ)
利用OS : win10 64bit
BTCSTのbuild : 070
(わかる方のみ)
利用PCの搭載CPU : XEON E5620 2.4GHz
利用PCの搭載メモリ量 : 12GB  

## ログ (報告のみ)

2018/04/22 14:34:34: 価格987331で指値買いエントリーを実行しました
2018/04/22 14:34:45:  CH: 指値エントリー 13eb6d7a-ac17-4a9a-9b70-de7e82be4966
2018/04/22 14:34:45:  EP: ポジション自動決済 bd3fa5b8-7885-4632-a74d-08a5bd59be42
2018/04/22 14:34:47: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/22 14:34:53:  EP: 注文全キャンセル 390afdd9-1383-4cf2-95ea-49093c89e46d
2018/04/22 14:34:53:  EP: 指値決済 321491fd-4690-4c94-88b3-777ff822cb61
2018/04/22 14:34:53: 自動利確現在価格指値注文を利益幅79で送信しました
2018/04/22 14:34:53:  CH: 指値決済 321491fd-4690-4c94-88b3-777ff822cb61
2018/04/22 14:34:53: ** 全キャンセル要求が正常に受け付けられました
2018/04/22 14:34:53:  CH: 注文全キャンセル 390afdd9-1383-4cf2-95ea-49093c89e46d
2018/04/22 14:35:01:  EP: 注文全キャンセル f3990639-66c7-4156-b7e0-723f6ed17d5d
2018/04/22 14:35:01:  EP: 指値決済 5956ae58-2c2d-462b-85de-e1b10b4aeb1a

**Comment by ghost** [comment]
ver1.01-build_003にて利確不具合の修正を行いました。
