### ISSUE TITLE
乖離監視システム

### ISSUE THREAD

**Issue by edamame501** [emu8/BTCST#86]
乖離が4.9以上ならいなご自動売買停止、4.8以下ならいなご自動売買作動になるようにしたいです。
## 実行環境 (報告のみ)
利用OS :  win10
BTCSTのbuild :  72
(わかる方のみ)  
利用PCの搭載CPU :  i7
利用PCの搭載メモリ量 :  8g

**Comment by ghost** [comment]
ver 1.01-build_014にてSFD状態でいなご自動売買のon/off機能を追加しました。
