### ISSUE TITLE
ポジション残りが発生します。

### ISSUE THREAD

**Issue by pocky777** [emu8/BTCST#87]
## 留意点

- 1 issueにつき 1個の要望 / 報告を記載してください。  
複数の要望 / 報告がある場合は、項目ごとにissueの作成をお願いいたします。

- 報告の場合はBTCST設定画面のスクリーンショットを、画面下部の"selecting them"より添付してください。  
[スクリーンショットの撮りかた](https://allabout.co.jp/gm/gc/20843/)

## 内容
今まで発生していなかったポジション残りが多発するようになりました。 

## 実行環境 (報告のみ)
利用OS : win10 64bit
BTCSTのbuild : 072
(わかる方のみ)
利用PCの搭載CPU : Core i7　7700K　4.20GHz
利用PCの搭載メモリ量 : 16GB

## ログ (報告のみ)
2018/04/29 6:28:11:  EP: いなご自動売買決済漏れポジション監視 67f00851-f3b2-4e9d-ae21-c675155000ea
2018/04/29 6:28:11: BTCST ver 1.00-build_072: initialized
2018/04/29 6:28:11: [1,"Connected","lightning_board_FX_BTC_JPY"]
2018/04/29 6:29:05: 127.0.0.1:55850と接続しました
2018/04/29 6:30:57:  EP: 指値エントリー 7c78d6ee-3754-41d7-9ffd-2e85f9dfaf03
2018/04/29 6:30:57: 価格1067776で指値売りエントリーを実行しました
2018/04/29 6:31:57: スケジュールされた非同期タスク(指値エントリー)の実行がタイムアウトしました（タイムアウト秒数: 60）
2018/04/29 6:31:57:  TH: 指値エントリー 7c78d6ee-3754-41d7-9ffd-2e85f9dfaf03
2018/04/29 6:31:57:  EP: 注文全キャンセル 90922dca-0fa5-4a8c-8a76-ca35ad3fdcf8
2018/04/29 6:32:57: スケジュールされた非同期タスク(注文全キャンセル)の実行がタイムアウトしました（タイムアウト秒数: 60）
2018/04/29 6:39:27:  EP: 指値エントリー a84d1578-9c2b-4483-80b7-bad266b251f1
2018/04/29 6:39:27: 価格1064008で指値買いエントリーを実行しました
2018/04/29 6:40:16: スケジュールされた非同期タスク(指値エントリー)(a84d1578-9c2b-4483-80b7-bad266b251f1)を実行中にエラーが発生しました: 指値注文が約定される前にいなごv2パワーバランスが逆転したので注文をキャンセルしました
2018/04/29 6:40:16:  EP: 注文全キャンセル c85880fa-e77d-4d20-afb9-70391eb5e16d
2018/04/29 6:40:46: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:40:52: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:40:52: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:40:53: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:40:53: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:40:57: 127.0.0.1:56109と接続しました
2018/04/29 6:41:03: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:41:03: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:41:03: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:41:16: スケジュールされた非同期タスク(注文全キャンセル)の実行がタイムアウトしました（タイムアウト秒数: 60）
2018/04/29 6:41:18: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:41:18: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:41:18:  EP: 注文全キャンセル 091b12fb-8d87-4cb1-b75c-8b31ab3f4b23
2018/04/29 6:41:18: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 6:41:18: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:41:18: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:41:18: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 6:41:19:  CH: 注文全キャンセル 091b12fb-8d87-4cb1-b75c-8b31ab3f4b23
2018/04/29 6:41:19: スケジュールされた非同期タスク(注文無し確認)(c566cf8f-65f9-4a42-9d20-b55e1b1e48bc)を実行中にエラーが発生しました: なんらかのタスクの処理がタイムアウトしたのでこの非同期タスクの処理をキャンセルしました
2018/04/29 6:41:19:  EP: 注文全キャンセル 8ecb7cf6-690f-4579-a72b-698bb2a3b372
2018/04/29 6:41:19: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 6:41:20:  CH: 注文全キャンセル 8ecb7cf6-690f-4579-a72b-698bb2a3b372
2018/04/29 6:53:06:  EP: 指値エントリー a8a45966-5e52-47ea-b365-0d80d157fb93
2018/04/29 6:53:06: 価格1061049で指値買いエントリーを実行しました
2018/04/29 6:53:06: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 6:53:15: スケジュールされた非同期タスク(指値エントリー)(a8a45966-5e52-47ea-b365-0d80d157fb93)を実行中にエラーが発生しました: 指値注文が約定される前にいなごv2パワーバランスが逆転したので注文をキャンセルしました
2018/04/29 6:53:15:  EP: 注文全キャンセル 18d75814-4772-429c-8e05-9f38c500ac37
2018/04/29 6:53:15: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 6:53:16:  CH: 注文全キャンセル 18d75814-4772-429c-8e05-9f38c500ac37
2018/04/29 6:57:02: 127.0.0.1:56109との接続を切断しました
2018/04/29 6:57:03: 127.0.0.1:56454と接続しました
2018/04/29 6:59:18:  EP: 指値エントリー 5fc78a9f-3dc7-4d63-b60b-47127baaf5ec
2018/04/29 6:59:18: 価格1063501で指値買いエントリーを実行しました
2018/04/29 6:59:18: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 6:59:19: スケジュールされた非同期タスク(指値エントリー)(5fc78a9f-3dc7-4d63-b60b-47127baaf5ec)を実行中にエラーが発生しました: 指値注文が約定される前にいなごv2パワーバランスが逆転したので注文をキャンセルしました
2018/04/29 6:59:19:  EP: 注文全キャンセル 51cca4dc-faa8-4c79-8727-39af267e1d68
2018/04/29 6:59:19: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 6:59:21:  CH: 注文全キャンセル 51cca4dc-faa8-4c79-8727-39af267e1d68
2018/04/29 7:02:08:  EP: 指値エントリー 35208e3e-1c48-4c61-b5c5-202044fa69bb
2018/04/29 7:02:08: 価格1064608で指値買いエントリーを実行しました
2018/04/29 7:02:09: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 7:02:44: スケジュールされた非同期タスク(指値エントリー)(35208e3e-1c48-4c61-b5c5-202044fa69bb)を実行中にエラーが発生しました: 指値注文が約定される前にいなごv2パワーバランスが逆転したので注文をキャンセルしました
2018/04/29 7:02:44:  EP: 注文全キャンセル 92ab1f07-85e3-4d06-a2fe-12ff85d9d9f0
2018/04/29 7:02:44: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 7:02:46:  CH: 注文全キャンセル 92ab1f07-85e3-4d06-a2fe-12ff85d9d9f0
2018/04/29 7:03:58:  EP: 指値エントリー 19f252ea-55fb-4f2f-bd80-c2141d43b35a
2018/04/29 7:03:58: 価格1065520で指値買いエントリーを実行しました
2018/04/29 7:03:59: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 7:04:26: スケジュールされた非同期タスク(指値エントリー)(19f252ea-55fb-4f2f-bd80-c2141d43b35a)を実行中にエラーが発生しました: 指値注文が約定される前にいなごv2パワーバランスが逆転したので注文をキャンセルしました
2018/04/29 7:04:26:  EP: 注文全キャンセル 589e24ed-d1bc-4019-9cc1-eb587b528c57
2018/04/29 7:04:26: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 7:04:28:  CH: 注文全キャンセル 589e24ed-d1bc-4019-9cc1-eb587b528c57
2018/04/29 7:27:02: 127.0.0.1:56454との接続を切断しました
2018/04/29 7:27:03: 127.0.0.1:57104と接続しました
2018/04/29 7:57:02: 127.0.0.1:57104との接続を切断しました
2018/04/29 7:57:03: 127.0.0.1:57737と接続しました
2018/04/29 8:27:02: 127.0.0.1:57737との接続を切断しました
2018/04/29 8:27:03: 127.0.0.1:58388と接続しました
2018/04/29 8:57:02: 127.0.0.1:58388との接続を切断しました
2018/04/29 8:57:03: 127.0.0.1:59053と接続しました
2018/04/29 9:27:02: 127.0.0.1:59053との接続を切断しました
2018/04/29 9:27:04: 127.0.0.1:59690と接続しました
2018/04/29 9:57:02: 127.0.0.1:59690との接続を切断しました
2018/04/29 9:57:03: 127.0.0.1:60263と接続しました
2018/04/29 10:27:02: 127.0.0.1:60263との接続を切断しました
2018/04/29 10:27:03: 127.0.0.1:60864と接続しました
2018/04/29 10:57:02: 127.0.0.1:60864との接続を切断しました
2018/04/29 10:57:03: 127.0.0.1:61512と接続しました
2018/04/29 11:27:02: 127.0.0.1:61512との接続を切断しました
2018/04/29 11:27:03: 127.0.0.1:62326と接続しました
2018/04/29 11:57:02: 127.0.0.1:62326との接続を切断しました
2018/04/29 11:57:03: 127.0.0.1:62917と接続しました
2018/04/29 12:27:02: 127.0.0.1:62917との接続を切断しました
2018/04/29 12:27:03: 127.0.0.1:63533と接続しました
2018/04/29 12:57:02: 127.0.0.1:63533との接続を切断しました
2018/04/29 12:57:03: 127.0.0.1:64318と接続しました
2018/04/29 13:27:02: 127.0.0.1:64318との接続を切断しました
2018/04/29 13:27:03: 127.0.0.1:65071と接続しました
2018/04/29 13:57:02: 127.0.0.1:65071との接続を切断しました
2018/04/29 13:57:03: 127.0.0.1:49468と接続しました
2018/04/29 14:13:56:  EP: 成行決済 88e3566f-d0bc-49c4-a3d9-1497c267aa52
2018/04/29 14:13:56: 全強制成行決済注文を送信しました
2018/04/29 14:14:02: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 14:14:04:  EP: 注文全キャンセル 450196ab-d6a6-4076-a426-02ffd14811e7
2018/04/29 14:14:04: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 14:14:04: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文無し確認)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 14:14:05:  EP: 指値エントリー 9edfa99b-c724-4fb6-b678-107087cc13a9
2018/04/29 14:14:05: 価格1081809で指値売りエントリーを実行しました
2018/04/29 14:14:05: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 14:14:05:  CH: 成行決済 88e3566f-d0bc-49c4-a3d9-1497c267aa52
2018/04/29 14:14:05: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 14:15:04: スケジュールされた非同期タスク(注文全キャンセル)の実行がタイムアウトしました（タイムアウト秒数: 60）
2018/04/29 14:15:04: スケジュールされた非同期タスク(指値エントリー)の実行がタイムアウトしました（タイムアウト秒数: 60）
2018/04/29 14:15:04:  TH: 指値エントリー 9edfa99b-c724-4fb6-b678-107087cc13a9
2018/04/29 14:15:04:  EP: 注文全キャンセル 08293c4f-baab-4b52-ba65-6dbd4488e3ae
2018/04/29 14:15:06: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 14:15:07:  CH: 注文全キャンセル 08293c4f-baab-4b52-ba65-6dbd4488e3ae
2018/04/29 14:22:03:  EP: 指値エントリー d08246c6-15cd-450b-9dc8-201f13fccf22
2018/04/29 14:22:03: 価格1080360で指値売りエントリーを実行しました
2018/04/29 14:22:10: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 14:22:29: スケジュールされた非同期タスク(指値エントリー)(d08246c6-15cd-450b-9dc8-201f13fccf22)を実行中にエラーが発生しました: 指値注文が約定される前にいなごv2パワーバランスが逆転したので注文をキャンセルしました
2018/04/29 14:22:29:  EP: 注文全キャンセル 5a683a73-ffa0-4b3c-bb64-e2cda23ebaf1
2018/04/29 14:22:29: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 14:22:31:  CH: 注文全キャンセル 5a683a73-ffa0-4b3c-bb64-e2cda23ebaf1
2018/04/29 14:25:47:  EP: 指値エントリー 5ddc84b1-e22c-4284-8de2-c4fcae84eaea
2018/04/29 14:25:47: 価格1080360で指値売りエントリーを実行しました
2018/04/29 14:25:47: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 14:26:37: スケジュールされた非同期タスク(指値エントリー)(5ddc84b1-e22c-4284-8de2-c4fcae84eaea)を実行中にエラーが発生しました: 指値注文が約定される前にいなごv2パワーバランスが逆転したので注文をキャンセルしました
2018/04/29 14:26:37:  EP: 注文全キャンセル 92630fb9-f594-4b05-af56-3e020460694c
2018/04/29 14:26:38: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 14:26:40:  CH: 注文全キャンセル 92630fb9-f594-4b05-af56-3e020460694c
2018/04/29 14:27:02: 127.0.0.1:49468との接続を切断しました
2018/04/29 14:27:03: 127.0.0.1:50256と接続しました
2018/04/29 14:38:27:  EP: 指値エントリー b98b935b-fdab-481f-be0d-115387b861c3
2018/04/29 14:38:27: 価格1081649で指値売りエントリーを実行しました
2018/04/29 14:38:28: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 14:39:27: スケジュールされた非同期タスク(指値エントリー)の実行がタイムアウトしました（タイムアウト秒数: 60）
2018/04/29 14:39:27:  TH: 指値エントリー b98b935b-fdab-481f-be0d-115387b861c3
2018/04/29 14:39:27:  EP: 注文全キャンセル 86269ec3-3c5b-4d8f-ab4b-d35cf72630cc
2018/04/29 14:39:27: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 14:39:29:  CH: 注文全キャンセル 86269ec3-3c5b-4d8f-ab4b-d35cf72630cc
2018/04/29 14:42:41:  EP: 指値エントリー 1339116c-8ef2-47c3-887d-9b562c9e236a
2018/04/29 14:42:41: 価格1080449で指値売りエントリーを実行しました
2018/04/29 14:42:42: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 14:43:05:  CH: 指値エントリー 1339116c-8ef2-47c3-887d-9b562c9e236a
2018/04/29 14:43:05:  EP: ポジション自動決済 3357f64f-29e0-45a1-ab61-36e913778eba
2018/04/29 14:43:06:  EP: 指値決済 601ebf2c-327f-488c-8d6b-a16698190067
2018/04/29 14:43:06: 一度に一つだけ実行される様スケジュールされた非同期タスク(指値決済)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 14:43:06: 自動利確指定利確幅指値注文を価格1079949(指定利益幅500)で送信しました
2018/04/29 14:43:06: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 14:43:06:  CH: 指値決済 601ebf2c-327f-488c-8d6b-a16698190067
2018/04/29 14:43:16:  EP: 注文全キャンセル e8d3a74c-f78e-40ba-b363-3c281cf02024
2018/04/29 14:43:16: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 14:43:16:  CH: ポジション自動決済 3357f64f-29e0-45a1-ab61-36e913778eba
2018/04/29 14:43:16: 一度に一つだけ実行される様スケジュールされた非同期タスク(注文全キャンセル)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 14:43:17:  CH: 注文全キャンセル e8d3a74c-f78e-40ba-b363-3c281cf02024
2018/04/29 14:57:02: 127.0.0.1:50256との接続を切断しました
2018/04/29 14:57:03: 127.0.0.1:51093と接続しました
2018/04/29 14:59:09:  EP: 指値エントリー 45a26bb2-f585-4133-941f-32911f5ee94f
2018/04/29 14:59:09: 価格1080452で指値買いエントリーを実行しました
2018/04/29 14:59:09: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 15:00:03: スケジュールされた非同期タスク(指値エントリー)(45a26bb2-f585-4133-941f-32911f5ee94f)を実行中にエラーが発生しました: 指値注文が約定される前にいなごv2パワーバランスが逆転したので注文をキャンセルしました
2018/04/29 15:00:03:  EP: 注文全キャンセル 7d869970-e47b-4068-8b22-aa3f658777f7
2018/04/29 15:00:05: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 15:00:06:  CH: 注文全キャンセル 7d869970-e47b-4068-8b22-aa3f658777f7
2018/04/29 15:01:07:  EP: 指値エントリー 7ee14886-3de6-4354-9ad3-65b9845ded2d
2018/04/29 15:01:07: 価格1081208で指値売りエントリーを実行しました
2018/04/29 15:01:07: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 15:01:13:  CH: 指値エントリー 7ee14886-3de6-4354-9ad3-65b9845ded2d
2018/04/29 15:01:14:  EP: ポジション自動決済 9b6651f5-0a86-4e78-85ed-e724bbb5c852
2018/04/29 15:01:14:  EP: 指値決済 b6110a33-cc17-4d2e-b7c6-a7055c9a2cc0
2018/04/29 15:01:14: 自動利確指定利確幅指値注文を価格1080708(指定利益幅500)で送信しました
2018/04/29 15:01:14: 一度に一つだけ実行される様スケジュールされた非同期タスク(指値決済)がまだ残っているためこの非同期タスクの実行がキャンセルされました
2018/04/29 15:01:14: ** 注文が正常に受け付けられました（取引所の負荷状況によってはポジションリストが更新されるまでに時間がかかる場合があります）
2018/04/29 15:01:15:  CH: 指値決済 b6110a33-cc17-4d2e-b7c6-a7055c9a2cc0
2018/04/29 15:02:13: スケジュールされた非同期タスク(ポジション自動決済)の実行がタイムアウトしました（タイムアウト秒数: 60）
2018/04/29 15:02:13:  TH: ポジション自動決済 9b6651f5-0a86-4e78-85ed-e724bbb5c852
2018/04/29 15:02:14:  EP: 注文全キャンセル 54609c4b-a0ec-4507-93e0-4ec4ebbb1878
2018/04/29 15:02:14: ** 全キャンセル要求が正常に受け付けられました
2018/04/29 15:02:15:  CH: 注文全キャンセル 54609c4b-a0ec-4507-93e0-4ec4ebbb1878
2018/04/29 15:27:03: 127.0.0.1:51093との接続を切断しました
2018/04/29 15:27:04: 127.0.0.1:51773と接続しました
2018/04/29 15:57:02: 127.0.0.1:51773との接続を切断しました
2018/04/29 15:57:03: 127.0.0.1:52422と接続しました
2018/04/29 16:27:02: 127.0.0.1:52422との接続を切断しました
2018/04/29 16:27:03: 127.0.0.1:53079と接続しました
2018/04/29 16:57:02: 127.0.0.1:53079との接続を切断しました
2018/04/29 16:57:03: 127.0.0.1:53706と接続しました
2018/04/29 17:27:02: 127.0.0.1:53706との接続を切断しました
2018/04/29 17:27:03: 127.0.0.1:54368と接続しました

![default](https://user-images.githubusercontent.com/38398451/39404932-fb5bd99a-4bd6-11e8-8a88-c18771937f38.PNG)

**Comment by ghost** [comment]
ver1.01-build_003にてポジション残りの対策を行いました。
なお、0.01未満の端数ポジション残りについては以降のアップデートで修正予定です。
