### ISSUE TITLE
【要望】V73現指連打の注文回数がV65に比べて遥かに少ないので改善してほしい。【裁量】

### ISSUE THREAD

**Issue by Misoji-Kun** [emu8/BTCST#88]
V65だと連打1秒間に3回以上入ったのですが、
V73だと1秒間に1回ほどしか入らないので地味に困ってます。（一度の注文なんとかこうたらのエラーが間に挟まる）
取引量が減少してるなか生き残るには素早い反応が非常に大事になってくるので、V65と同程度の連打が最新版でも使えると非常に助かります。
まだ現状もっさり感がある。

あと今後もV65は裁量のひとつの完成形だと思うので使えるようにしていただけると非常に助かります。

**Comment by ghost** [comment]
ver1.01-build_003にて裁量時の連打が不足なく行えるようになりました。
今後処理の最適化を更に行い、よりスムーズに注文を行えるよう改善いたします。
