### ISSUE TITLE
フルナンピン利確時の二重注文

### ISSUE THREAD

**Issue by emu8** [emu8/BTCST#9]
昨晩も数名で話題になっていたフルナンピン利確時の二重注文の件で、今先程この設定ではありえない数字で入っていたのでSSを取りました。
今後の開発の中で対応できたら嬉しいなと思います。

**Comment by ghost** [comment]
v1.01より、大幅な動作の軽量化・注文処理の正常化ならびに内部処理の最適化によるハングアップ・エラー等の対策を行いました。
最新のbuildで同現象が再度発生した際にもう一度issue投稿いただけますと幸いです。
