### ISSUE TITLE
注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。

### ISSUE THREAD

**Issue by iketa0** [emu8/BTCST#92]
## 留意点

- 1 issueにつき 1個の要望 / 報告を記載してください。  
複数の要望 / 報告がある場合は、項目ごとにissueの作成をお願いいたします。

- 報告の場合はBTCST設定画面のスクリーンショットを、画面下部の"selecting them"より添付してください。  
[スクリーンショットの撮りかた](https://allabout.co.jp/gm/gc/20843/)

## 内容
今日、BTCST065でトレードをしているとログに度々『注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。』と、表示されるようになり、注文が遅くなっているのを体感しました。
『注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。』のログがあるのと、ないのとでは、明らかに注文スピードが違います。
このエラーを解決したいので、どうかご教授頂きたいです。

※最新版では、現指の連打スピードが遅すぎるため使っておらず、どうかこの065で解決したいと思っています。

## 実行環境 (報告のみ)
利用OS :  windows10 64bit
BTCSTのbuild :  065
(わかる方のみ)  
利用PCの搭載CPU :  i3 8350k
利用PCの搭載メモリ量 :  16GB

## ログ (報告のみ)
2018/05/16 19:20:29: BTCST ver 1.00-build_065: initialized
2018/05/16 19:20:29: [1,"Connected","lightning_board_FX_BTC_JPY"]
2018/05/16 19:20:42: 127.0.0.1:58523と接続しました
2018/05/16 19:20:46: 127.0.0.1:58574と接続しました
2018/05/16 19:23:37: 127.0.0.1:58523との接続を切断しました
2018/05/16 19:23:38: 127.0.0.1:58644と接続しました
2018/05/16 19:24:03: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました
2018/05/16 19:24:39: 注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。
2018/05/16 19:29:19: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました
2018/05/16 19:33:22: 注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。
2018/05/16 19:33:29: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました
2018/05/16 19:44:01: 注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。
2018/05/16 19:44:18: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました
2018/05/16 19:49:24: 127.0.0.1:59107と接続しました
2018/05/16 19:50:35: 注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。
2018/05/16 19:50:41: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました
2018/05/16 19:51:54: 127.0.0.1:58644との接続を切断しました
2018/05/16 19:52:11: 127.0.0.1:59213と接続しました
2018/05/16 20:01:46: 127.0.0.1:59462と接続しました
2018/05/16 20:02:26: 127.0.0.1:59462との接続を切断しました
2018/05/16 20:07:24: 注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。
2018/05/16 20:07:29: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました
2018/05/16 20:10:55: 注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。
2018/05/16 20:11:19: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました
2018/05/16 20:17:05: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました
2018/05/16 20:17:22: 注文要求処理結果をAPIで取得中にエラーが発生しました：1 つ以上のエラーが発生しました。
2018/05/16 20:17:40: ポジション解消に成功したので指値注文と予約注文を全てキャンセルしました

**Comment by ghost** [comment]
v1.01より、大幅な動作の軽量化・注文処理の正常化ならびに内部処理の最適化によるハングアップ・エラー等の対策を行いました。
最新のbuildで同現象が再度発生した際にもう一度issue投稿いただけますと幸いです。
