### ISSUE TITLE
ver 075以降BTCST上でchromeを起動するとPCがフリーズするようになった。

### ISSUE THREAD

**Issue by mixixk** [emu8/BTCST#95]
ver 074以前は起きなかったのですが外部チャート、bFLightningのボタンを押してchomeをBTCST上で起動させてしばらくするとPCがフリーズするようになりました。拡張が原因かと思ってゲストモードで起動しても同じ現象が起こります。BTCSTとchromeを別々で起動すると問題なく可動できます。BTCSTにchromeを埋め込む際になんらかの不具合が起きてるものかと思います。

**Comment by mixixk** [comment]
Windows7 のデスクトップテーマを無効にしてから起動するとchromeのブラウザが嵌め込み出来なくなってたみたいです、有効にしたら問題なくウィンドウが嵌め込みされました。

**Comment by ghost** [comment]
ユーザ様による解決によりクローズいたします。
また、今後BTCSTへの外部チャート・lightning埋め込みを軽い動作で行えるようなアップデートを予定しております。
